version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:18.04
    steps:
      - run:
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt update
            apt install python3 python3-pip git -y
            git clone --depth 5 "$CIRCLE_REPOSITORY_URL" --branch "$CIRCLE_BRANCH"
            cd *
            pip3 install -r requirements.txt
            python3 main.py