version: 2.1
jobs:
  build:
    docker: 
      - image: python:3.8-slim
    steps:
      - run:
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt update
            apt install git -y
            git clone https://github.com/BobbySJohnson/Discord-Bot.git
            cd Discord-Bot
            pip3 install -r requirements.txt
            python3 main.py